config/routes.rb
Rails.application.routes.draw do
  root "alibis#index"

  resources :alibis
end

app/models/alibi.rb
class Alibi < ApplicationRecord
    validates :title, presence: true, length: { minimum: 1 }
    validates :body, presence: true, length: { minimum: 12 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/alibis_controller.rb
class AlibisController < ApplicationController
  http_basic_authenticate_with name: "Tatas", password: "TatasPassword", except: [:index, :show]

  def index
    @alibis = Alibi.all
  end

  def show
    @alibi = Alibi.find(params[:id])
  end

  def new
    @alibi = Alibi.new
  end

  def create
    @alibi = Alibi.new(alibi_params)

    if @alibi.save
      redirect_to @alibi
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def alibi_params
      params.require(:alibi).permit(:title, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/alibi_helper.rb
module AlibiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alibis/index.html.erb
<div class="list">
    <% @alibis.reverse.each do |alibi| %>
        <a class="alibi" href="<%= alibi_path(alibi) %>">
            <span class="logotext">The Daily Alibi</span>
            <span><%= alibi.title %></span>
            <span class="small"><%= alibi.created_at.strftime('%b %d %Y') %></span>
        </a>
    <% end %>
    <% if @alibis.length == 0 %>
        <span>There are no alibis yet...</span>
    <% end %>
</div>

app/views/alibis/new.html.erb
<h1 class="title">New Alibi</h1>

<div id="form">
<%= form_with model: @alibi do |form| %>
    <div>
        <%= form.label :title%><br>
        <%= form.text_field :title%>
        <div class="errors">
            <% @alibi.errors.full_messages_for(:title).each do |message| %>
                <span style="color: red"><%= message %></span>
            <% end %>
        </div>
    </div>
    <br>
    <div>
        <%= form.label :body%><br>
        <%= form.text_area :body%>
        <div class="errors">
            <% @alibi.errors.full_messages_for(:body).each do |message| %>
                <span style="color: red"><%= message %></span>
            <% end %>
        </div>
    </div>
    <br>
    <div>
        <%= form.submit %>
    </div>
<% end %>
</div>

app/views/alibis/show.html.erb
<div class="show">
<h1 class="title"><%= @alibi.title %></h1>
<span class="small"><%= @alibi.created_at.strftime('%b %d %Y') %></span>
<p class="p"><%= @alibi.body %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheDailyAlibi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application.css' %>
    <%= stylesheet_link_tag 'https://fontlibrary.org//face/chomsky' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <div class="row">
        <a href="/" class="home">Home</a>
        <a href="/" class="logo">The Daily Alibi</a>
      </div>
      <hr class="topSplit">
    </nav>
    <%= yield %>
  </body>
</html>